INSERT INTO CARTELA(MEDIC_FILIALA_ID, CLIENT_ID, DATA_ADRESARII, DIAGNOZA, PRESCRIPTII, COST)
VALUES (:MEDIC_FILIALA_ID, :CLIENT_ID, :DATA_ADRESARII, :DIAGNOZA, :PRESCRIPTII, :COST)

UPDATE CARTELA SET MEDIC_FILIALA_ID=:MEDIC_FILIALA_ID,
				   CLIENT_ID=:CLIENT_ID,
				   DIAGNOZA=:DIAGNOZA,
				   PRESCRIPTII=:PRESCRIPTII,
				   COST=:COST
WHERE CARTELA_ID = :CARTELA_ID

DELETE CARTELA WHERE CARTELA_ID=:CARTELA_ID

