SELECT M.NUME+' '+M.PRENUME AS MEDIC, CL.NUME+' '+CL.PRENUME AS MEDIC, * 
FROM MEDIC M INNER JOIN MEDIC_FILIALA MF ON MF.MEDIC_ID=M.MEDIC_ID
             INNER JOIN FILIALA F ON F.FILIALA_ID=MF.FILIALA_ID
			 INNER JOIN CARTELA C ON C.MEDIC_FILIALA_ID = MF.MEDIC_FILIALA_ID
			 INNER JOIN CLIENT CL ON CL.CLIENT_ID = C.CLIENT_ID
WHERE CL.CLIENT_ID=:CLIENT_ID
