SELECT *,(SELECT STOCK FROM STOCK SK WHERE SK.PRODUSE_ID=P.PRODUSE_ID) AS STOCK_REAL

		  FROM RECEPTIE R INNER JOIN FIRMA_OPERATOR F ON R.FIRMA_OPERATOR_ID=F.FIRMA_OPERATOR_ID
                         INNER JOIN OPERATOR O ON O.OPERATOR_ID=F.OPERATOR_ID
                         INNER JOIN PRODUSE P ON P.PRODUSE_ID=R.PRODUSE_ID
                         INNER JOIN UNIT_MASURA UM ON UM.UNIT_MASURA_ID=R.UNIT_MASURA_ID
                         INNER JOIN FACTURA_REC FK ON FK.FACTURA_REC_ID=R.FACTURA_REC_ID
                         INNER JOIN EMITENT E ON E.EMITENT_ID=FK.EMITENT_ID
WHERE FK.FACTURA_REC_ID=:FACTURA_REC_ID