-- CREAREA BD CLINICA --

-- 1) client --
-- 2) medici --
-- 3) filiale --
-- 4) cartoteca (info pacient) --

CREATE DATABASE CLINICA

USE CLINICA

-- CREAREA TABELELOR --

CREATE TABLE CLIENT
(
	CLIENT_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(50),
	PRENUME VARCHAR(50),
	DATA_NASTERII DATE,		
	IDNP VARCHAR(13),
	TELEFON VARCHAR(11),
	ADRESA VARCHAR(100)
)

CREATE TABLE MEDIC
(
	MEDIC_ID INT PRIMARY KEY IDENTITY(1,1),
	NUME VARCHAR(50),
	PRENUME VARCHAR(50),
	FUNCTIA VARCHAR(40)
)

CREATE TABLE FILIALA
(	
	FILIALA_ID INT PRIMARY KEY IDENTITY(1,1),
	DENUMIRE VARCHAR(40),
	ADRESA VARCHAR(100),
	TELEFON VARCHAR(9)
)

CREATE TABLE MEDIC_FILIALA
(
	MEDIC_FILIALA_ID INT PRIMARY KEY IDENTITY(1,1),
	FILIALA_ID INT FOREIGN KEY REFERENCES FILIALA(FILIALA_ID),
	MEDIC_ID INT FOREIGN KEY REFERENCES MEDIC(MEDIC_ID)
)

CREATE TABLE CARTELA
(
	CARTELA_ID INT PRIMARY KEY IDENTITY(1,1),
	MEDIC_FILIALA_ID INT FOREIGN KEY REFERENCES MEDIC_FILIALA(MEDIC_FILIALA_ID),
	CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
	DATA_ADRESARII DATE,
	DIAGNOZA VARCHAR(100),
	PRESCRIPTII VARCHAR(100),
	COST DECIMAL(9,2) DEFAULT 0
)

-- INSERAREA DATELOR --
INSERT INTO FILIALA(DENUMIRE, ADRESA, TELEFON)
VALUES ('FILIALA 1', 'STR. GHEORGHE ASACHI 14', 'O78922343'),
	   ('FILIALA 2', 'BD. STEFAN CEL MARE 5', '061322343'),
	   ('FILIALA 3', 'STR. MIRON COSTIN 55/2', '076656432')

INSERT INTO MEDIC(NUME, PRENUME, FUNCTIA)
VALUES ('RUSU', 'ION', 'CHIRURG DENTO-ALVEOLAR'),
	   ('CIOTU', 'CORNEL', 'STOMATOLOG GENERAL'),
	   ('ALBA', 'EUGENIA', 'CHIRURG STOMATOLOGIC'),
	   ('ESANU', 'SERGIU', 'PARODONTOLOG'),
	   ('STRATAN', 'ALEXANDRA', 'ORTODONT DENTO-FACIAL'),
	   ('CAZACU', 'CRISTIAN', 'ENDODONT')

INSERT INTO MEDIC_FILIALA(MEDIC_ID, FILIALA_ID)
VALUES (1, 1),
	   (2, 2),
	   (3, 3),
	   (4, 3),
	   (5, 1),
	   (6, 2)